project:
  type: website

website:
  title: "WiscWeeds.info"
  reader-mode: true
  google-analytics: "G-VTH6CK2TEW"
  
  navbar:
    pinned: true
    background: darkred
    #logo: 
    
    left:
      - text: "Blog Posts"
        file: index.qmd
      - text: "About Us"
        file: about.qmd
      - text: "Research Reports"
        file: reports.qmd
      - text: "WiscWeeds Team"
        file: team.qmd
      - text: "Werle Bio"
        file: werle.qmd
      
    right: 
      - icon: twitter
        text: "Twitter"
        href: https://twitter.com/WiscWeeds
     # - icon: google scholar
      #  href: https://scholar.google.com/citations?hl=en&user=Bmu_aPYAAAAJ&view_op=list_works&sortby=pubdate
      #- icon: github
      #  href: https://github.com/WiscWeeds
      #- icon: envelope
      #  href: mailto:rwerle@wisc.edu
        
  page-footer: Copyright 2023 WiscWeeds (Dr. Rodrigo Werle). Powered by [Quarto](https://quarto.org/), [RStudio](https://posit.co/), & [GitHub](https://github.com/). 
   
format:
  html:
    theme: default
    css: styles.css

editor: visual